[package]
name = "libmahjong-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
libmahjong-specs = { git = "https://github.com/realliance/libmahjong-specs.git", branch = "dist/rust" }

libc = "0.2.171"
strum = "0.27"
strum_macros = "0.27"
